# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/builds.html for details

# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

mkdocs:
  configuration: mkdocs.yml
